var skills = ['Sword', 'Lance', 'Axe', 'Bow', 'Brawl', 'Reason', 'Faith', 'Authority', 'Heavy Armor', 'Riding', 'Flying'];
var talents = {//SLABBRFAHRF
  'Byleth':     's---s-hs---',
  'Edelgard':   's-sw-hwss--',
  'Hubert':     '-hws-sws--w',
  'Ferdinand':  'sss-----hs-',
  'Linhardt':   '--w-wss----',
  'Caspar':     '--swsw-w---',
  'Bernadetta': 'wswsw---wh-',
  'Dorothea':   's----sh--ww',
  'Petra':      's-ss-ww---s',
  'Dimitri':    'ssw--w-s-h-',
  'Dedue':      '-ss-s-w-sww',
  'Felix':      's--ssh-w---',
  'Ashe':       '-hss-w-----',
  'Sylvain':    '-ssw-h---s-',
  'Mercedes':   'wwwh-ss-w--',
  'Annette':    '--sw-s-sw--',
  'Ingrid':     'ss-------ss',
  'Claude':     'swhs--ws-ss',
  'Lorenz':     '-s--ws---s-',
  'Raphael':    '--swsw--sw-',
  'Ignatz':     's--s-h-s--w',
  'Lysithea':   'hww--sssw--',
  'Marianne':   'sh--w-s-wss',
  'Hilda':      '-ss---wwh--',
  'Leonie':     '-s-s-----s-',
  'Seteth':     'SSS----S-wS',
  'Flayn':      '-s---hs-ww-',
  'Hanneman':   '---S-S--wSw',
  'Manuela':    'S----wS-w-S',
  'Gilbert':    '-ss--w--s-w',
  'Alois':      '--S-Sw--S--',
  'Catherine':  'S---Sw-----',
  'Shamir':     '-S-S--w----',
  'Cyril':      '-sss-ww--ss',
  'Jeritza':    'ss--s-ww-s-',
  'Jeralt':     'ss--www--s-',
  'Rhea':       'S???SSS????',
  'Yuri':       'swwh-sss-ww',
  'Balthus':    'swswshs-s-w',
  'Constance':  's-w-hs-sw-s',
  'Hapi':       '--h-ws-wwss',
  'Anna':       'S-SS-wSw-h-',
};
var classes = {                                        //SLABBRFAHRF
  'Myrmidon':        {'tier': 'Beginner',     'skills': 'D          '},
  'Soldier':         {'tier': 'Beginner',     'skills': ' D         '},
  'Fighter':         {'tier': 'Beginner',     'skills': '  DDD      '},
  'Monk':            {'tier': 'Beginner',     'skills': '     DD    '},
  'Lord':            {'tier': 'Intermediate', 'skills': 'd      C   '},
  'Mercenary':       {'tier': 'Intermediate', 'skills': 'C          '},
  'Thief':           {'tier': 'Intermediate', 'skills': 'C          '},
  'Cavalier':        {'tier': 'Intermediate', 'skills': ' C       D '},
  'Pegasus Knight':  {'tier': 'Intermediate', 'skills': ' C        D'},
  'Brigand':         {'tier': 'Intermediate', 'skills': '  C        '},
  'Armored Knight':  {'tier': 'Intermediate', 'skills': '  C     D  '},
  'Archer':          {'tier': 'Intermediate', 'skills': '   C       '},
  'Brawler':         {'tier': 'Intermediate', 'skills': '    C      '},
  'Mage':            {'tier': 'Intermediate', 'skills': '     C     '},
  'Dark Mage':       {'tier': 'Intermediate', 'skills': '     C     '},
  'Priest':          {'tier': 'Intermediate', 'skills': '      C    '},
  'Swordmaster':     {'tier': 'Advanced',     'skills': 'A          '},
  'Hero':            {'tier': 'Advanced',     'skills': 'B C        '},
  'Assassin':        {'tier': 'Advanced',     'skills': 'B  C       '},
  'Paladin':         {'tier': 'Advanced',     'skills': ' B       B '},
  'Warrior':         {'tier': 'Advanced',     'skills': '  A        '},
  'Fortress Knight': {'tier': 'Advanced',     'skills': '  B     B  '},
  'Wyvern Rider':    {'tier': 'Advanced',     'skills': '  B       C'},
  'Sniper':          {'tier': 'Advanced',     'skills': '   A       '},
  'Grappler':        {'tier': 'Advanced',     'skills': '    A      '},
  'Warlock':         {'tier': 'Advanced',     'skills': '     A     '},
  'Dark Bishop':     {'tier': 'Advanced',     'skills': '     A     '},
  'Bishop':          {'tier': 'Advanced',     'skills': '      A    '},
  'Trickster':       {'tier': 'Special',      'skills': 'B     B    '},
  'War Monk/Cleric': {'tier': 'Special',      'skills': '    b c    '},
  'Dark Flier':      {'tier': 'Special',      'skills': '     b    C'},
  'Valkyrie':        {'tier': 'Special',      'skills': '     B   B '},
  'Falcon Knight':   {'tier': 'Master',       'skills': 'CA        b'},
  'Wyvern Lord':     {'tier': 'Master',       'skills': ' CA       A'},
  'Mortal Savant':   {'tier': 'Master',       'skills': 'A    b     '},
  'Great Knight':    {'tier': 'Master',       'skills': '  b     Ab '},
  'Bow Knight':      {'tier': 'Master',       'skills': ' C A     A '},
  'Dark Knight':     {'tier': 'Master',       'skills': ' C   b   A '},
  'Holy Knight':     {'tier': 'Master',       'skills': '      b  A '},
  'War Master':      {'tier': 'Master',       'skills': '  A A      '},
  'Gremory':         {'tier': 'Master',       'skills': '     AA    '},
};
